### ISSUE TITLE
Bloater: Long Method

### ISSUE THREAD

**Issue by Ohwelleh** [kianapaz/seng371#20]
This appears to be of the code smell Long Method. We could create two additional functions that contain the code located within each if block. These functions would need a few parameters passed to them, but wouldn't be too hard to implement.

https://github.com/kianapaz/seng371/blob/a2833d5b73e018ebc46ebc374232ab8900c3c28d/freeplane/src/main/java/org/freeplane/main/application/BorderLayoutWithVisibleCenterComponent.java#L11-L59

**Comment by kianapaz** [comment]
Totally agreed. Freeplane seems to have a lot of Bloaters: Long Methods. I found a couple of similar files, https://github.com/kianapaz/seng371/blob/main/freeplane_plugin_svg/src/main/java/org/freeplane/plugin/svg/SvgViewerFactory.java is another with a bloated method. 
I searched for Object-Orientation Abusers: Switch Statements but I didn't find any

**Comment by amadansododoo** [comment]
I also found a few more in this file: https://github.com/kianapaz/seng371/blob/main/freeplane/src/main/java/org/freeplane/features/export/mindmapmode/ExportAction.java
