### ISSUE TITLE
Dispensable: Dead Code

### ISSUE THREAD

**Issue by kianapaz** [kianapaz/seng371#22]
https://github.com/kianapaz/seng371/blob/a2833d5b73e018ebc46ebc374232ab8900c3c28d/freeplane_plugin_jsyntaxpane/src/main/java/org/freeplane/plugin/jsyntaxpane/NodeIdHighLighter.java#L147-L162

Commented out code, this dead code is unhelpful because we don't know if it was ever useful, if it causes error in a program or if it is deprecated.

**Comment by Ohwelleh** [comment]
We are going to not refactor this piece of code because it is located within a plugin directory. This directory appears to be related to JavaScript syntax in someway. Thus, making it hard to understand what its goal is and how to be unit test it.
