### ISSUE TITLE
Dispensable: Duplicate code

### ISSUE THREAD

**Issue by amadansododoo** [kianapaz/seng371#23]
https://github.com/kianapaz/seng371/blob/main/freeplane/src/main/java/org/freeplane/main/mindmapmode/UpdateCheckAction.java
Found instances of duplicate code: lines 334 to 343 and 380 to 389
We could extract the method to refactor it

**Comment by Ohwelleh** [comment]
Code has been moved to a method instead. Currently working on the unit test for this.
