### ISSUE TITLE
Identify 1-3 features to implement or bugs to fix.

### ISSUE THREAD

**Issue by kianapaz** [kianapaz/seng371#28]
1-3 depending on the difficulty of the feature or bug fix.

**Comment by kianapaz** [comment]
Here is the issue tracker for Freeplane: https://github.com/freeplane/freeplane/issues
We can choose to fix some of these issues, since that would make finding the issues easier

**Comment by amadansododoo** [comment]
Noticed there is no "fit to page size" or "zoom to fit page". This could be an interesting feature to add.

**Comment by kianapaz** [comment]
Austin identified a toggle dark feature
Ama identified a zoom extra feature option
Kiana identified a node style change feature request.
